version: '3.8'

volumes:
  static_volume:
  media_volume:

services:
  backend:
    build: backend
    command: python3 manage.py runserver
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - backend
