version: '3.8'


volumes:
    esdata:
      driver: local

services:
  backend:
    build: backend
    ports:
      - "8000"
    depends_on:
      - elasticsearch
    env_file:
      - backend/.env

  frontend:
    build: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200"
    restart: always